FROM ubuntu:20.04

# Install prerequisites
RUN apt-get update && \
    apt-get install -y curl gnupg2 tar ca-certificates bzip2 && \
    rm -rf /var/lib/apt/lists/*

# Add Microsoft repository
RUN curl https://packages.microsoft.com/keys/microsoft.asc | tee /etc/apt/trusted.gpg.d/microsoft.asc
RUN curl https://packages.microsoft.com/config/ubuntu/20.04/prod.list | tee /etc/apt/sources.list.d/mssql-release.list

# Install SQLCMD
RUN apt-get update && \
    ACCEPT_EULA=Y apt-get install -y mssql-tools && \
    echo 'export PATH="$PATH:/opt/mssql-tools/bin"' >> ~/.bashrc

ENV PATH="/opt/mssql-tools/bin:${PATH}"

ENTRYPOINT ["sqlcmd"]
